import type { ApiReferenceLocalization } from '@scalar/types/api-reference'

export const scalarCzechTranslations = {
  common: {
    additionalProperties: 'další vlastnosti',
    deprecated: 'zastaralé',
    description: 'Popis',
    discriminator: 'Diskriminátor',
    format: 'Formát',
    greaterThan: 'větší než',
    httpMethod: 'HTTP metoda',
    keys: 'klíče',
    lessThan: 'menší než',
    maxLength: 'max. délka',
    minLength: 'min. délka',
    multipleOf: 'násobek',
    nullable: 'může být null',
    path: 'Cesta',
    propertyNames: 'názvy vlastností',
    pattern: 'Vzor',
    readOnly: 'pouze pro čtení',
    required: 'povinné',
    hideValues: 'Skrýt hodnoty',
    showAllValues: 'Zobrazit všechny hodnoty',
    type: 'Typ',
    unique: 'unikátní',
    values: 'hodnoty',
    writeOnly: 'pouze pro zápis',
  },
  search: {
    label: 'Hledat',
    inputLabel: 'Zadejte hledaný výraz',
    open: 'Otevřít vyhledávání',
    placeholder: 'Hledat…',
    clear: 'Vymazat hledání',
    keyboardShortcut: 'Klávesová zkratka:',
    results: 'Výsledky hledání',
    navigate: 'Procházet',
    select: 'Vybrat',
    instructions: 'Šipkami procházejte výsledky, Enterem vyberte a psaním filtrujte',
    entryHeading: 'Nadpis',
    entryOperation: 'Operace',
    entryTag: 'Štítek',
    entryTagGroup: 'Skupina štítků',
  },
  navigation: {
    introduction: 'Úvod',
    closeGroup: 'Sbalit skupinu',
    closeMenu: 'Zavřít nabídku',
    openGroup: 'Rozbalit skupinu',
    openMenu: 'Otevřít nabídku',
    operations: 'Operace',
    endpoints: 'Endpointy: {name}',
    showAllEndpoints: 'Zobrazit všechny endpointy: {name}',
    sidebarFor: 'Navigace pro {name}',
    mainContent: 'API dokumentace pro {name}',
    collapsed: 'Sbaleno',
  },
  server: {
    label: 'Server',
    select: 'Vyberte server',
  },
  info: { termsOfService: 'Obchodní podmínky' },
  clientLibraries: {
    heading: 'Klientské knihovny',
    more: 'Další',
    selectAll: 'Vybrat ze všech klientů',
  },
  operation: {
    body: 'Tělo',
    cookies: 'Cookies',
    headers: 'Hlavičky',
    pathParameters: 'Parametry cesty',
    queryParameters: 'Parametry dotazu',
    requestBody: 'Tělo požadavku',
    responses: 'Odpovědi',
    testRequest: 'Otestovat požadavek',
    selectedContentType: 'Vybraný typ obsahu',
    hideHeaders: 'Skrýt hlavičky',
    showHeaders: 'Zobrazit hlavičky',
    callbacks: 'Zpětná volání',
  },
  response: {
    exampleResponses: 'Příklady odpovědí',
    noBody: 'Bez těla',
    showSchema: 'Zobrazit schéma',
    status: 'Stav',
  },
  schema: {
    example: 'Příklad',
    examples: 'Příklady',
    default: 'Výchozí',
    schema: 'Schéma',
    emptyObject: 'Prázdný objekt',
    showAdditionalProperties: 'Zobrazit další vlastnosti',
    childAttributes: 'Vnořené atributy',
    hideChildAttributes: 'Skrýt {name}',
    showChildAttributes: 'Zobrazit {name}',
    forName: 'pro {name}',
    showSchemaDetails: 'Zobrazit podrobnosti schématu',
    oneOf: 'Jedna z možností',
    anyOf: 'Libovolná z možností',
    allOf: 'Všechny možnosti',
    not: 'Není',
    unknownType: 'neznámý typ',
  },
  download: {
    openapi: 'Stáhnout OpenAPI dokument',
    asyncapi: 'Stáhnout AsyncAPI dokument',
  },
  models: { label: 'Datové modely' },
  actions: {
    copyLink: 'Kopírovat odkaz',
    copyLinkTo: 'Kopírovat odkaz na {name}',
    copyToClipboard: 'Zkopírovat odkaz do schránky',
    copyEndpointUrl: 'Kopírovat URL endpointu',
    showMore: 'Zobrazit více',
  },
  footer: { poweredByScalar: 'Běží na Scalaru' },
  authentication: {
    title: 'Autentizace',
    accepts: 'Přijímá',
    allOf: 'všechny možnosti:',
    authentication: 'autentizace',
    optional: 'Autentizace volitelná',
    oneOf: 'jedna z možností:',
    required: 'Vyžaduje autentizaci',
    requires: 'Vyžaduje',
    scopes: 'OAuth oprávnění',
  },
} satisfies NonNullable<ApiReferenceLocalization['translations']>
